demographic_data: false
dropout_prob: 0.5
hidden_dims:
- 256
- 128
input_dim: 45
learning_rate: 0.0001
loss_type: rmse
lr_scheduler: true
output_dim: 1
predict_fam_lik: false
target_name: process_ongoing
use_batch_norm: false
weight_decay: true
